version: '3.8'

services:
  postgres:
    image: postgres:16
    container_name: postgres_api_users
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: api_users_db
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: